version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - certificates:/certs
    environment:
      - sslcert:/certs/portainer.crt
      - sslkey:/certs/portainer.key
    ports:
      - 9443:9443
      - 8000:8000
      - 8081:9000
    networks:
      - infrastructure

#  portainer-reverse-proxy:
#    image: portainer/portainer-ce:latest
#    container_name: portainer-reverse-proxy
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 9443:9443
#    networks:
#      - infrastructure


volumes:
  portainer_data:
  certificates:
    external: true  
  
networks:
  infrastructure:
    ipam:
      config:
        - subnet: 172.31.0.0/16
